// Mocks generated by Mockito 5.4.5 from annotations
// in country_list/test/src/features/presentation/country_bloc/country_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:country_list/src/common/entities/app_error.dart' as _i6;
import 'package:country_list/src/common/entities/no_params.dart' as _i8;
import 'package:country_list/src/features/country_list/domain/entities/country_entity.dart'
    as _i7;
import 'package:country_list/src/features/country_list/domain/repositories/country_repositories.dart'
    as _i2;
import 'package:country_list/src/features/country_list/domain/usecases/get_country.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCountryRepository_0 extends _i1.SmartFake
    implements _i2.CountryRepository {
  _FakeCountryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCountry].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCountry extends _i1.Mock implements _i4.GetCountry {
  MockGetCountry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryRepository get countryRepository => (super.noSuchMethod(
        Invocation.getter(#countryRepository),
        returnValue: _FakeCountryRepository_0(
          this,
          Invocation.getter(#countryRepository),
        ),
      ) as _i2.CountryRepository);

  @override
  _i5.Future<_i3.Either<_i6.AppError, List<_i7.CountryEntity>>> call(
          _i8.NoParams? noParams) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [noParams],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.AppError, List<_i7.CountryEntity>>>.value(
                _FakeEither_1<_i6.AppError, List<_i7.CountryEntity>>(
          this,
          Invocation.method(
            #call,
            [noParams],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AppError, List<_i7.CountryEntity>>>);
}
